---
version: "3.8"

services:
  db:
    container_name: optom-api-db
    image: "postgres:13.6"
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    restart: always
  app:
    container_name: optom-api-app
    build: .
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    ports:
      - ${APP_PORT:-8000}:8000
    volumes:
      - ./app/:/code/app/
      - ./tests/:/code/tests/

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
