"""modifying user

Revision ID: 18d04de73c3a
Revises: 7002fd888c92
Create Date: 2022-08-24 18:15:40.135998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18d04de73c3a"
down_revision = "7002fd888c92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "full_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
