---
name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: create-env
        name: Create .env file
        run: |
          touch .env
          echo 'POSTGRES_DB=postgres' >> .env
          echo 'POSTGRES_PASSWORD=postgres' >> .env
          echo 'POSTGRES_PORT=5433' >> .env
          echo 'POSTGRES_SERVER=db' >> .env
          echo 'POSTGRES_HOST_AUTH_METHOD=trust' >> .env
          echo 'APP_PORT=8001' >> .env
          echo 'PIPENV_VENV_IN_PROJECT=1' >> .env
          echo 'SECRET_KEY=SECRET_KEY' >> .env

      - id: docker-compose
        name: Build with docker-compose
        run: |
          docker-compose up --build -d
          docker exec -it optom-api-app sh -c "pytest"
