---
name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: docker-compose
        name: Build with docker-compose
        run: |
          docker-compose --env-file '.env.local' up --build -d
          docker exec -it optom-api-app sh -c "pytest"
