---
name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: docker-compose
        name: Docker compose
        uses: isbang/compose-action@v1.2.0
